version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-github"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ogzmsqj8lsqo"
s3_prefix = "sam-app-github"
region = "ca-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
